export const
  AUTH_INITIATED = 'AUTH_INITIATED',
  AUTH_SUCCESS = 'AUTH_SUCCESS',
  AUTH_FAILURE = 'AUTH_FAILURE',
  CHECK_LOGIN = 'CHECK_LOGIN',
  LOGOUT = 'LOGOUT',
  LOGOUT_SUCCESS = 'LOGOUT_SUCCESS',
  TEAMS_INITIATE = 'TEAMS_INITIATE',
  TEAMS_SUCCESS = 'TEAMS_SUCCESS',
  TEAMS_FAILURE = 'TEAMS_FAILURE',

  GROUPS_INITIATE = 'GROUPS_INITIATE',
  GROUPS_SUCCESS = 'GROUPS_SUCCESS',
  GROUPS_FAILURE = 'GROUPS_FAILURE'



